![Numpy](img/numpy.png)

Bienvenue dans ce notebook d'initiation à **NumPy**, une bibliothèque essentielle pour la data science avec Python.

🎯 Objectif : Comprendre l'essentiel de NumPy

---

## 📌 Sommaire :
1. Création de tableaux
2. Dimensions et forme
3. Indexation & slicing
4. Opérations vectorielles
5. Fonctions statistiques
6. Manipulation et fusion
7. Broadcasting

---


# Introduction

NumPy (**Numerical Python**) est la bibliothèque de base pour le calcul scientifique avec Python. Elle permet de manipuler des structures de données puissantes appelées **arrays** ou **tableaux**, optimisées pour la performance et la simplicité d’usage. NumPy est utilisé par presque toutes les bibliothèques de l’écosystème <a href='https://pydata.org/'>PyData</a> (comme **Pandas**, **Scikit-learn**, **SciPy**) et constitue une compétence fondamentale pour tout data scientist ou ingénieur en machine learning.


<img src="img/numpy_foundation.png" alt="Numpy" style="display:block; margin-left:auto; margin-right:auto;">

**Pourquoi Numpy ?**

Contrairement aux listes Python classiques, les tableaux NumPy sont :
- Plus **rapides** et moins gourmands en mémoire
- Facilement extensibles à plusieurs dimensions (**vecteurs**, **matrices**, **tenseurs**)
- Compatibles avec des **opérations vectorisées** et du **broadcasting**
- Intégrés dans toutes les bibliothèques majeures de la **data science**

**Chargement de la librairie Numpy**

In [3]:
import numpy as np

# 1. 🎲 Création de tableaux NumPy

## 1.1. Depuis des objets Python

NumPy permet de créer facilement des tableaux numériques notamment à parti de listes Python

In [4]:
my_list = [5, 10, 15]           # liste Python contenant trois entiers
my_array = np.array(my_list)    # convertit cette liste en tableau numpy, ce qui permet ensuite d’appliquer des opérations vectorielles

display(my_list)
display(my_array)

[5, 10, 15]

array([ 5, 10, 15])

## 1.2. Tableaux 1D et 2D : vecteurs et matrices

La structure de base de NumPy est le `tableau` (array). Il peut être :

**1D** : vecteur

**2D** : matrice

ou **nD** (plusieurs dimensions)

In [5]:
# Vecteur 1D
v = np.array([1, 2, 3])

# Matrice 2D
m = np.array([[1, 2], [3, 4]])

display(type(v))
display(v)
print("---------------")
display(type(m))
display(m)

numpy.ndarray

array([1, 2, 3])

---------------


numpy.ndarray

array([[1, 2],
       [3, 4]])

🧠 **À retenir** : une matrice 2D peut contenir une seule ligne ou une seule colonne, mais reste bien en deux dimensions.

### 🧩 Exercices

> Créez et affichez un vecteur contenant les entiers de 10 à 20

In [ ]:
# Votre code ici
vector = np.array([11,12,11,14,15,16,17,18,19,20])

print(vector)

[11 12 11 14 15 16 17 18 19 20]


> Créez et affichez une matrice 3x3 avec les entiers de 1 à 9

In [9]:
# Votre code ici
v = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 1.3. Séquences numériques

Il est facile de générer facilement des suites de nombres avec Numpy.

In [10]:
sequence_1 = np.arange(0, 10, 2)    # crée une suite de nombres allant de 0 à 8 avec un pas de 2
sequence_2 = np.linspace(0, 1, 5)   # génère 5 valeurs également espacées entre 0 et 1 inclus

display(sequence_1)
display(sequence_2)

array([0, 2, 4, 6, 8])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 🧩 Exercices

> Créez un tableau avec des valeurs entre 0 et 20 espacées de 5

In [13]:
# Votre code ici
v =  np.arange(0,20,5)
print(v)

[ 0  5 10 15]


> Utilisez ``linspace`` pour créer un tableau de 50 valeurs entre -1 et 1

In [14]:
# Votre code ici
v = np.linspace(-1,1,50)

print(v)

[-1.         -0.95918367 -0.91836735 -0.87755102 -0.83673469 -0.79591837
 -0.75510204 -0.71428571 -0.67346939 -0.63265306 -0.59183673 -0.55102041
 -0.51020408 -0.46938776 -0.42857143 -0.3877551  -0.34693878 -0.30612245
 -0.26530612 -0.2244898  -0.18367347 -0.14285714 -0.10204082 -0.06122449
 -0.02040816  0.02040816  0.06122449  0.10204082  0.14285714  0.18367347
  0.2244898   0.26530612  0.30612245  0.34693878  0.3877551   0.42857143
  0.46938776  0.51020408  0.55102041  0.59183673  0.63265306  0.67346939
  0.71428571  0.75510204  0.79591837  0.83673469  0.87755102  0.91836735
  0.95918367  1.        ]


## 1.4. Génération de données aléatoires

NumPy propose également un module random pour créer des tableaux remplis de valeurs aléatoires.

In [15]:
# Entiers aléatoires (entre 0 et 10, exclu)
object_1 = np.random.randint(0, 10)           # un seul entier aléatoire entre 0 et 9
object_2 = np.random.randint(0, 10, (3, 3))   # matrice 3x3 d'entiers aléatoires entre 0 et 9

# Flottants aléatoires uniformes entre 0 et 1
object_3 = np.random.rand(4)                 # vecteur de 4 flottants tirés d'une distribution uniforme [0, 1)
object_4 = np.random.rand(4, 4)              # matrice 4x4 de flottants tirés d'une distribution uniforme [0, 1)

# Flottants aléatoires selon une loi normale (moyenne = 0, écart-type = 1)
object_5 = np.random.randn(4)                # vecteur de 4 flottants selon une loi normale centrée réduite
object_6 = np.random.randn(4, 4)             # matrice 4x4 de flottants selon une loi normale centrée réduite              

display(object_1)
display(object_2)
display(object_3)
display(object_4)
display(object_5)
display(object_6)

2

array([[6, 3, 6],
       [7, 2, 0],
       [5, 0, 3]])

array([0.33919278, 0.31054823, 0.69278192, 0.506306  ])

array([[0.81435599, 0.3962291 , 0.98839025, 0.31081187],
       [0.98381066, 0.73483172, 0.82222161, 0.38799516],
       [0.26682777, 0.94677244, 0.73346365, 0.21826597],
       [0.30935144, 0.55186121, 0.52714819, 0.89380738]])

array([ 0.70399079, -0.34746609,  2.05050936, -0.72382969])

array([[-0.63106322,  1.56045629, -2.95640486, -0.27200784],
       [-0.78897611, -3.19313143, -0.37924459,  2.84116687],
       [ 0.24296372, -0.3635152 , -0.24305889, -0.58259804],
       [-0.40441551, -0.8394707 ,  0.09256199, -0.18278836]])

### 🧩 Exercices

> Générez un entier aléatoire entre 1 et 100

In [ ]:
nb = np.random.randint(1,101)

print(nb)

62


> Créez un tableau 1D de 10 entiers aléatoires entre 0 et 20

In [ ]:
v = np.random.randint(0,21, (1,10))[0]

print(v)

[19 18 18 19 13 13 10 12 12 12]


> Générez une matrice 5x5 d’entiers entre 0 et 9

In [34]:
v = np.random.randint(0, 10, (5, 5))
print(v)

[[0 7 2 9 0]
 [6 7 7 9 5]
 [3 9 9 8 2]
 [8 3 7 8 1]
 [6 1 4 6 4]]


> Générez un vecteur de 6 flottants aléatoires entre 0 et 1

In [35]:
v = np.random.rand(6)
print(v)

[0.39971693 0.8017883  0.09345053 0.19943489 0.33500984 0.42934854]


> Créez une matrice 3x3 de flottants aléatoires entre 0 et 1

In [36]:
v = np.random.rand(3,3)
print(v)

[[0.70985095 0.78280055 0.62254677]
 [0.12688116 0.9336587  0.8058325 ]
 [0.37017244 0.92980269 0.64849101]]


> Générez un vecteur de 8 valeurs suivant une loi normale (moyenne 0, écart-type 1)

In [37]:
v = np.random.randn(8)
print(v)

[ 1.98957107  1.46048682 -1.44763989 -0.69179765  1.62203893 -0.2420342
 -2.09403888 -0.61569062]


> Créez une matrice 4x4 de valeurs aléatoires selon une loi normale

In [38]:
v = np.random.randn(4, 4)
print(v)

[[-1.93686428  0.3632933   0.0192031  -1.11262538]
 [ 0.58838047 -1.07132004 -1.27387666  0.25383229]
 [ 0.32619781  2.33510192 -0.60710311  0.20828953]
 [-0.18353215  0.48140799  0.83665248  1.19911027]]


## 1.5. Tableaux pré-remplis

Numpy propose des fonctions pratiques pour créer rapidement des tableaux contenant des valeurs par défaut.

In [39]:
# Zéros
zeros = np.zeros(4)               # vecteur de 4 éléments contenant uniquement des zéros
zeros_matrix = np.zeros((4, 4))   # matrice 4x4 remplie de zéros

# Uns
ones = np.ones(4)                 # vecteur de 4 éléments contenant uniquement des uns
ones_matrix = np.ones((4, 4))     # matrice 4x4 remplie de uns

# Matrice identité 4x4 (matrice carrée avec des 1 sur la diagonale principale et des 0 ailleur.
# Elle joue un rôle similaire au nombre 1 pour la multiplication)
matrix_identity = np.eye(4)     


display(zeros)
display(zeros_matrix)

display(ones)
display(ones_matrix)

display(matrix_identity)

array([0., 0., 0., 0.])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 🧩 Exercices

> Créez un vecteur de 6 zéros

In [40]:
v = np.zeros(6)
print(v)

[0. 0. 0. 0. 0. 0.]


> Créez une matrice 3x5 remplie de zéros

In [42]:
v = np.zeros((3,5))
print(v)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


> Créez un vecteur de 10 uns

In [43]:
v = np.ones(10)
print(v)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


> Créez une matrice 2x3 remplie de uns

In [44]:
v = np.ones((2,3))
print(v)

[[1. 1. 1.]
 [1. 1. 1.]]


> Créez une matrice identité 8x8

In [45]:
v = np.eye(8)
print(v)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


# 2. 📐 Dimensions et forme des tableaux

Numpy offre des attributs très utiles pour explorer la structure des tableaux

In [46]:
# Tableau de 0 à 11 transformé en matrice 3x4 grâce à la méthode .reshape()
# ⚠️ Attention : le produit des dimensions passées à reshape (ici 3×4 = 12) 
# doit exactement correspondre au nombre total d’éléments dans le tableau initial. Sinon, NumPy renverra une erreur !
array = np.arange(12).reshape(3, 4)        

print("Tableau :\n", array, "\n")                     # affiche le tableau
print("Forme (shape) :", array.shape, "\n")           # affiche la forme du tableau
print("Nombre de dimensions :", array.ndim, "\n")     # affiche le nombre de dimensions
print("Nombre total d'éléments :", array.size, "\n")  # affiche le nombre d'éléments
print("Type de données (dtype) :", array.dtype, "\n") # affiche le type des données

Tableau :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Forme (shape) : (3, 4) 

Nombre de dimensions : 2 

Nombre total d'éléments : 12 

Type de données (dtype) : int64 



### 🧩 Exercice

> Créez une matrice de forme 6x2 à partir de np.arange().  
> Affichez sa forme, son nombre d’éléments, son nombre de dimensions.

In [48]:
array = np.arange(12).reshape(6,2)
print("shape", array.shape)
print("elements", array.size)
print("dimensions", array.ndim)

shape (6, 2)
elements 12
dimensions 2


> Créez un tableau contenant les nombres de 0 à 19, puis transformez-le en matrice de 4 lignes et 5 colonnes.

In [50]:
array = np.arange(20)
reshaped_array = array.reshape(4, 5)
print(array)
print(reshaped_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


> Vous disposez d’un tableau de 18 éléments. Quelles sont les trois formes possibles que vous pouvez lui donner avec reshape() en matrice 2D ?

In [51]:
array = np.arange(18)
reshaped1 = array.reshape(2, 9)
reshaped2 = array.reshape(9, 2)
reshaped3 = array.reshape(6, 3)

print(array)
print(reshaped1)
print(reshaped2)
print(reshaped3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


# 3. 🔍 Indexing & Slicing

Lorsque vous travaillez avec des tableaux ou matrices NumPy, il est essentiel de savoir accéder aux éléments, **extraire des lignes**, **des colonnes** ou **des sous-parties**. Cette opération s’appelle l’**indexing** (accès à un ou plusieurs éléments) et le **slicing** (extraction de tranches).

NumPy utilise une syntaxe très proche de celle des listes Python, mais adaptée aux tableaux multidimensionnels. Grâce à cela, vous pouvez :
- Accéder à une valeur précise dans un tableau 2D
- Extraire une ligne ou une colonne
- Récupérer plusieurs lignes ou colonnes avec des tranches (slices)
- Utiliser des conditions (masques logiques) pour filtrer certains éléments

Dans les exemples suivants, nous allons manipuler une matrice 3x4 pour explorer ces différentes possibilités.

In [52]:
# Matrice de travail
matrix = np.arange(12).reshape(3, 4)

print("Matrice :\n", matrix)

Matrice :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 3.1. Indexing

**Indexing** = accès à un seul élément ou un groupe précis via des **indices explicites**.

In [ ]:
print("Première ligne :", matrix[0])                # extrait toute la première ligne
print("Dernière ligne :", matrix[-1])               # extrait toute la dernière ligne
print("Première colonne :", matrix[:, 0])           # extrait tous les éléments de la 1ère colonne, sur toutes les lignes
print("Dernière colonne :", matrix[:, -1])          # extrait tous les éléments de la dernière colonne, sur toutes les lignes
print("Élément ligne 0, colonne 2 :", matrix[0, 2]) # extrait'élément situé à la 1ère ligne (index 0) et à la 3e colonne (index 2)

## 3.2. Slicing

**Slicing** = accès à une plage continue d’éléments avec l’opérateur : `(start:stop:step)`.

In [ ]:
print("Lignes 0 et 1 :\n", matrix[0:2], "\n")               # extrait les deux premières lignes (lignes 0 et 1 incluses, ligne 2 exclue)
print("Colonnes 1 et 2 :\n", matrix[:, 1:3], "\n")          # extrait toutes les lignes mais seulement les colonnes 1 et 2 (3 exclue)
print("Colonnes 0, 2, ... :\n", matrix[:, ::2], "\n")       # extrait toutes les lignes mais une colonne sur deux (colonne 0, 2...)
print("Éléments > 5 :\n", matrix[matrix > 5], "\n")         # extrait tous les éléments dont la valeur est strictement supérieure à 5
print("Éléments pairs :\n", matrix[matrix % 2 == 0], "\n")  # extrait tous les éléments qui sont des nombres pairs (reste = 0 quand divisé par 2)

### 🧩 Exercice

> À partir d’un tableau `array = np.arange(35).reshape(5, 7)`, répondez aux questions suivantes :  
> 1. Affichez l’élément situé à la 3e ligne et 5e colonne.  
> 2. Affichez toute la 2e ligne du tableau. 
> 3. Affichez toute la dernière colonne. 
> 4. Affichez les trois premières lignes du tableau. 
> 5. Affichez les colonnes 2 à 5 de toutes les lignes. 
> 6. Affichez les 3 derniers éléments de la 4e ligne.
> 7. Affichez une ligne sur deux (lignes 0, 2, 4).  
> 8. Affichez une colonne sur trois (colonnes 0, 3, 6).
> 9. Affichez tous les éléments strictement supérieurs à 25.
> 10. Affichez tous les éléments impairs du tableau.
> 11. Affichez tous les éléments compris entre 10 et 20 inclus.
> 12. Remplacez l’élément en ligne 1, colonne 4 par 999.
> 13. Remplacez tous les éléments multiples de 7 par -7.
> 14. Remplacez la 3e colonne par des zéros.

In [87]:
array = np.arange(35).reshape(5, 7)
print(array)
print("1: ",array[2, 4])
print("2: ",array[1])
print("3: ",array[-1])
print("4: ",array[0:3])
print("5: ",array[:, 2:6])
print("6: ",array[3, 4:7])
print("7: ",array[::2])
print("8:",array[:, ::3])
print("9:",array[array > 25])
print("10:",array[array % 2 == 1])
interval = array[array >= 10]
interval = interval[interval <= 20]
print("11:",interval )
array[0,3] = 999
print("12:",array)

array[np.where(array % 7 == 0)] = -7

print("13:",array)

array[:, 2] = 0
print("14", array)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
1:  18
2:  [ 7  8  9 10 11 12 13]
3:  [28 29 30 31 32 33 34]
4:  [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
5:  [[ 2  3  4  5]
 [ 9 10 11 12]
 [16 17 18 19]
 [23 24 25 26]
 [30 31 32 33]]
6:  [25 26 27]
7:  [[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]
8: [[ 0  3  6]
 [ 7 10 13]
 [14 17 20]
 [21 24 27]
 [28 31 34]]
9: [26 27 28 29 30 31 32 33 34]
10: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
11: [10 11 12 13 14 15 16 17 18 19 20]
12: [[  0   1   2 999   4   5   6]
 [  7   8   9  10  11  12  13]
 [ 14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34]]
13: [[ -7   1   2 999   4   5   6]
 [ -7   8   9  10  11  12  13]
 [ -7  15  16  17  18  19  20]
 [ -7  22  23  24  25  26  27]
 [ -7  29  30  31  32  33  34]]
14 [[ -7   1   0 999   4   5   6]
 [ -7   8   0  10  11  

# 4. ➕ Opérations vectorielles

Lorsqu’on travaille avec des tableaux NumPy (vecteurs ou matrices), on peut effectuer des opérations mathématiques directement sur l’ensemble des éléments, sans utiliser de boucles. On parle d’**opérations vectorielles** ou **opérations élément par élément**.

Cela permet :
- d’écrire du code plus simple et plus lisible,
- d’obtenir des calculs bien plus rapides grâce à l’optimisation interne de NumPy,
- de manipuler facilement des données numériques comme dans les domaines de la data science ou du machine learning.

**🤖 Pourquoi les opérations vectorielles sont essentielles en machine learning ?**

Dans le machine learning, on travaille en permanence avec :
- des vecteurs : chaque ligne de données (ex : un utilisateur avec ses caractéristiques) est un vecteur,
- des matrices : un ensemble de données (ex : tous les utilisateurs) forme une matrice,
- et des opérations mathématiques rapides pour entraîner et utiliser les modèles.


In [88]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

# Addition élément par élément
print("Addition :", x + y)  # [11 22 33]

# Soustraction élément par élément
print("Soustraction :", x - y)  # [-9 -18 -27]

# Multiplication élément par élément (produit Hadamard)
print("Multiplication :", x * y)  # [10 40 90]

# Division élément par élément
print("Division :", y / x)  # [10. 10. 10.]

# Exponentiation
print("Carrés de x :", x ** 2)  # [1 4 9]

# Produit scalaire (dot product)
print("Produit scalaire (x @ y) :", x @ y)  # 140
print("Produit scalaire (np.dot) :", np.dot(x, y))  # 140

# Norme (longueur du vecteur)
print("Norme de x :", np.linalg.norm(x))  # sqrt(1^2 + 2^2 + 3^2) = 3.7416...

Addition : [11 22 33]
Soustraction : [ -9 -18 -27]
Multiplication : [10 40 90]
Division : [10. 10. 10.]
Carrés de x : [1 4 9]
Produit scalaire (x @ y) : 140
Produit scalaire (np.dot) : 140
Norme de x : 3.7416573867739413


### 🧩 Exercices

> Soit `x = np.array([2, 4, 6])` et `y = np.array([1, 3, 5])`  
> 1. Calculez x + y  
> 2. Calculez x - y  
> 3. Calculez x * y (multiplication élément par élément)  
> 4. Calculez x / y (division élément par élément)

In [89]:
x = np.array([2,4,6])
y = np.array([1,3,5])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


> Reprenez les vecteurs x et y ci-dessus  
> 1. Calculez le carré de chaque élément de x  
> 2. Calculez le double de chaque élément de y  
> 3. Ajoutez 10 à tous les éléments de x

In [90]:
print (x ** 2)
print(y * 2)
print(x + 10)

[ 4 16 36]
[ 2  6 10]
[12 14 16]


> Soit `x = np.array([1, 2, 3])` et `y = np.array([4, 5, 6])`  
> 1. Calculez le **produit scalaire** de x et y avec `@`  
> 2. Calculez le produit scalaire avec `np.dot()`  
> 3. Vérifiez que les deux résultats sont identiques

In [91]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x @ y)
print(np.dot(x, y))

32
32


> Soit `v = np.array([3, 4])`  
> 1. Calculez la **norme** de v (indice : `np.linalg.norm`)  
> 2. Normalisez v (divisez chaque élément par la norme)  
> 3. Vérifiez que la norme du vecteur normalisé vaut 1

In [95]:
v = np.array([3,4])
norm = np.linalg.norm(v)
normalized_v = v / norm
print(norm)
print(v / norm)
print(np.linalg.norm(normalized_v))

5.0
[0.6 0.8]
1.0


> Créez deux vecteurs a et b de taille 5, remplis avec des entiers de votre choix  
> 1. Faites la somme, la différence et le produit terme à terme  
> 2. Calculez la somme totale des éléments de a et de b  
> 3. Calculez la moyenne des éléments de a

In [110]:
a = np.random.randint(100, size=(5))
b = np.random.randint(100, size=(5))
print("a: ", a)
print("b: ", b)

sum = np.sum(a + b)
print(sum)

mean = np.mean(a)
print(mean)

a:  [22 15 96 85 54]
b:  [12  7 36 48 96]
471
54.4


# 5. 📊 Fonctions statistiques utiles

NumPy propose de nombreuses fonctions pour analyser rapidement des données numériques : **maximum**, **minimum**, **moyenne**, **écart-type**, **somme**, etc. Ces fonctions permettent d’obtenir des indicateurs statistiques simples sur un tableau, qu’il soit 1D (vecteur) ou 2D (matrice).

## 5.1. Vecteur 1D

In [111]:
# Tableau de 10 entiers aléatoires entre 0 et 99
arr = np.random.randint(0, 100, (10,))

print("Tableau :", arr)
print("Max :", arr.max())                # Valeur maximale du tableau
print("Min :", arr.min())                # Valeur minimale du tableau
print("Moyenne :", arr.mean())           # Moyenne arithmétique
print("Écart-type :", arr.std())         # Écart-type (dispersion des valeurs)
print("Somme :", arr.sum())              # Somme de tous les éléments
print("Indice du max :", arr.argmax())   # Position (indice) de la valeur maximale
print("Indice du min :", arr.argmin())   # Position (indice) de la valeur minimale

Tableau : [71 10 21 13 48 73 80 59 89 76]
Max : 89
Min : 10
Moyenne : 54.0
Écart-type : 27.932060432413504
Somme : 540
Indice du max : 8
Indice du min : 1


## 5.2. Matrice 2D

In [112]:
# matrice 4x5 d'entiers aléatoires entre 0 et 99
matrix = np.random.randint(0, 100, (4, 5))

print("Matrice :\n", matrix, "\n")

print("Moyenne globale :", matrix.mean(), "\n")              # Moyenne de tous les éléments
print("Moyenne par ligne :", matrix.mean(axis=1), "\n")      # Moyenne de chaque ligne
print("Moyenne par colonne :", matrix.mean(axis=0), "\n")    # Moyenne de chaque colonne
print("Somme par colonne :", matrix.sum(axis=0), "\n")       # Somme de chaque colonne

Matrice :
 [[24 94 65 77 66]
 [58  4 90 81 83]
 [28 63 62 14 62]
 [68 37  0 11 57]] 

Moyenne globale : 52.2 

Moyenne par ligne : [65.2 63.2 45.8 34.6] 

Moyenne par colonne : [44.5  49.5  54.25 45.75 67.  ] 

Somme par colonne : [178 198 217 183 268] 



### 🧩 Exercices

> Générez un tableau de 15 entiers aléatoires entre 1 et 100.  
> Affichez la valeur maximale, la valeur minimale et leur écart.

In [113]:
array = np.random.randint(100, size=(15))
print(array.max())
print(array.min())
print(array.max() - array.min())

79
3
76


> Générez un tableau de 20 entiers aléatoires entre 0 et 50.  
> Affichez la somme, la moyenne et la variance.

In [115]:
array = np.random.randint(1, 51, size=(20))
print(array.sum())
print(array.mean())
print(array.var())

515
25.75
211.9875


> Créez une matrice 5x4 d’entiers aléatoires entre 0 et 99.  
> Affichez la moyenne de chaque ligne et la moyenne de chaque colonne.

In [119]:
array = np.random.randint(100, size=(5, 4))
print(array)
print(array.mean(axis=1))
print(array.mean(axis=0))

[[46 82 67 88]
 [22 19 62 49]
 [60 50 63 98]
 [28 54 79 92]
 [72 45 14 65]]
[70.75 38.   67.75 63.25 49.  ]
[45.6 50.  57.  78.4]


> Générez une matrice 6x3 d'entiers aléatoires.  
> Affichez l’indice du maximum global, puis l’indice du maximum de chaque ligne.

In [122]:
array = np.random.randint(100, size=(6, 3))
print(array)
print(array.argmax())
print(array.argmax(axis=1))

[[44 95 95]
 [63 64 56]
 [53 96 51]
 [54 67 41]
 [93  9 77]
 [92 55  1]]
7
[1 1 1 1 0 0]


> Créez un tableau de 12 flottants aléatoires entre 0 et 1.  
> Comptez combien de valeurs sont supérieures à la moyenne.

In [128]:
array = np.random.rand(12)
print(array)
mean = array.mean()
print(mean)
sup = array[array > mean]
print(len(sup))

[0.6058745  0.94952675 0.96844028 0.90817338 0.4727141  0.61968753
 0.6463207  0.66327075 0.9431987  0.10814779 0.35993119 0.69909496]
0.6620317203274465
6


> Générez un tableau de 50 entiers entre 10 et 100.  
> Calculez le 25e, le 50e (médiane) et le 75e percentile.

In [5]:
import numpy as np

array = np.random.randint(10, 101, size=(50))
array.sort()
print(array)
print(np.percentile(array, 25))
print(np.percentile(array, 50))
print(np.percentile(array, 75))

[ 15  15  19  20  21  22  24  26  27  28  29  30  30  34  37  38  38  39
  40  43  46  46  51  52  52  62  63  64  66  72  74  77  78  79  80  80
  80  84  86  88  91  92  92  93  96  96  98  99 100 100]
31.0
57.0
83.0


# 6. 🔧 Empilement et fusion de tableaux

Il est souvent nécessaire de combiner plusieurs tableaux NumPy pour former des structures plus grandes.  
Cela peut se faire en ajoutant des lignes (empilement vertical) ou des colonnes (empilement horizontal).

NumPy propose plusieurs fonctions pour cela :

- `np.vstack` : empilement dans le sens **vertical** (ajoute des lignes)
- `np.hstack` : empilement dans le sens **horizontal** (ajoute des colonnes)
- `np.concatenate` : fusion plus générale, où l’on choisit l’axe (`axis=0` pour les lignes, `axis=1` pour les colonnes)

⚠️ Pour que ces opérations fonctionnent, les **dimensions doivent être compatibles** :
- Pour empiler verticalement, les **nombres de colonnes doivent être identiques**
- Pour empiler horizontalement, les **nombres de lignes doivent être identiques**

In [6]:
a = np.array([[1, 2], [3, 4]])  # matrice 2x2
b = np.array([[5, 6]])          # matrice 1x2


# Empilement vertical : ajoute des lignes (mêmes nombres de colonnes requis)
vstacked = np.vstack([a, b])
print("Empilement vertical (vstack) :\n", vstacked, "\n")

# Empilement horizontal : ajoute des colonnes (mêmes nombres de lignes requis)
hstacked = np.hstack([a, a])
print("Empilement horizontal (hstack) :\n", hstacked, "\n")


# Fusion avec np.concatenate (plus général)
conc_v = np.concatenate([a, b], axis=0)  # même que vstack
print("Concaténation verticale :\n", conc_v, "\n")

conc_h = np.concatenate([a, a], axis=1)  # même que hstack
print("Concaténation horizontale :\n", conc_h, "\n")


# 💡 INFO :
# np.vstack([a, b]) et np.concatenate([a, b], axis=0) donnent exactement le même résultat :
# → ils empilent les tableaux verticalement (ajout de lignes).

# De même, np.hstack([a, a]) et np.concatenate([a, a], axis=1) sont aussi équivalents :
# → ils empilent les tableaux horizontalement (ajout de colonnes).

# ✅ vstack / hstack sont plus lisibles pour débuter,
# ✅ concatenate est plus flexible (surtout utile pour des tableaux à plus de 2 dimensions).

Empilement vertical (vstack) :
 [[1 2]
 [3 4]
 [5 6]] 

Empilement horizontal (hstack) :
 [[1 2 1 2]
 [3 4 3 4]] 

Concaténation verticale :
 [[1 2]
 [3 4]
 [5 6]] 

Concaténation horizontale :
 [[1 2 1 2]
 [3 4 3 4]] 



### 🧩 Exercices

> Créez deux matrices compatibles pour un empilement vertical :  
> - une matrice `a` de forme `(2, 3)`  
> - une matrice `b` de forme `(1, 3)`  
> - Utilisez `np.vstack()` pour les empiler.

In [9]:
a = np.random.randint(100, size=(2,3))
b = np.random.randint(100, size=(1,3))
print(a)
print(b)
stack = np.vstack([a,b])
print(stack)

[[52 38 84]
 [78 33 41]]
[[83  9 27]]
[[52 38 84]
 [78 33 41]
 [83  9 27]]


> Reprenez les mêmes matrices que précdemment et utilisez np.concatenate() avec axis=0 pour vérifier qu’on obtient le même résultat qu’avec vstack.

In [10]:
stack = np.concatenate([a,b], axis=0)
print(stack)

[[52 38 84]
 [78 33 41]
 [83  9 27]]


> Reprenez les mêmes matrices que précédemment et utilisez np.concatenate() avec axis=1 pour vérifier qu’on obtient le même résultat qu’avec hstack.

In [ ]:
ERROR AS INTENDED

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

# 7. 📡 Broadcasting (adaptation automatique des dimensions)

En NumPy, les opérations entre tableaux (addition, soustraction, etc.) nécessitent normalement que les formes (shape) soient **compatibles**.

Mais au lieu de lever une erreur quand les formes sont différentes, NumPy applique parfois automatiquement une règle intelligente d’adaptation des dimensions : c’est ce qu’on appelle le **broadcasting** (ou diffusion en français).

In [12]:
A = np.array([[1], [2], [3]])  # Matrice de forme (3, 1) : vecteur colonne
B = np.array([10, 20, 30])     # Vecteur ligne de forme (3,)

print("A.shape =", A.shape, "\n")    # Affiche la forme de A : (3, 1)
print("B.shape =", B.shape, "\n")    # Affiche la forme de B : (3,)

# NumPy étend automatiquement A horizontalement (comme si on le copiait 3 fois en colonnes) pour l’aligner avec B (qui est traité comme une ligne).
# Résultat : addition élément par élément dans une matrice de forme (3, 3)
print("Résultat du broadcasting :\n", A + B)

A.shape = (3, 1) 

B.shape = (3,) 

Résultat du broadcasting :
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### 🧩 Exercices

> Créez un vecteur `a = np.array([1, 2, 3])`.  
> Ajoutez le scalaire `5` à ce vecteur. Que se passe-t-il ?

In [13]:
a = np.array([1,2,3])
print(a + 5)

[6 7 8]


> Créez une matrice `M` de forme (3, 4) avec `np.ones((3, 4))`.  
> Créez un vecteur `v = np.array([10, 20, 30, 40])`.  
> Faites `M + v` et observez le résultat.

In [14]:
matrix = np.ones((3,4))
v = np.array([10,20,30,40])
print(matrix + v)

[[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]


> Créez une matrice `M = np.ones((3, 4))`.  
> Créez un vecteur colonne `v = np.array([[1], [2], [3]])`.  
> Faites `M + v`. Pourquoi cela fonctionne ?

In [ ]:
M = np.ones((3,4))
v = np.array([[1],[2],[3]])
print(M+v)

#chaque entrée de v est dupliquée sur toute la ligne

[[2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


> Créez `A = np.array([[1], [2], [3]])` (forme 3x1)  
> Créez `B = np.array([10, 20])` (forme 2,)  
> Essayez `A + B`. Que se passe-t-il ? Pourquoi ?

In [ ]:
A = np.array([[1],[2],[3]])
B = np.array([10, 20])
print(A+B)

#pour chaque entrée de A on applique le calcul avec les deux entrée de la ligne B

[[11 21]
 [12 22]
 [13 23]]


> Créez `X = np.ones((2, 3, 4))`  
> Créez `Y = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])` (forme 3x4)  
> Essayez `X + Y` et observez la forme du résultat.

In [20]:
x = np.ones((2,3,4))
print(x)
y = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(x+y)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[ 11.  21.  31.  41.]
  [ 51.  61.  71.  81.]
  [ 91. 101. 111. 121.]]

 [[ 11.  21.  31.  41.]
  [ 51.  61.  71.  81.]
  [ 91. 101. 111. 121.]]]


---
## ✅ Bravo !
Vous connaissez maintenant les bases essentielles de NumPy. Vous allez pouvoir aborder d'autres libriaries telles que **Pandas** ou **Scikit-learn**.